/* Generated By:JJTree: Do not edit this line. ASTarg_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTarg_list extends SimpleNode {
  public ASTarg_list(int id) {
    super(id);
  }

  public ASTarg_list(Minimp p, int id) {
    super(p, id);
  }
  
  public Object getValue()
  {
	  return this.jjtGetValue().toString();
  }
  @Override
  public Object interpret()
  {
	  // Go through children and add them to the list
	  String [] varNames = new String[this.jjtGetNumChildren()];
	  for(int i = 0; i < this.jjtGetNumChildren(); i++)
	  {
		  varNames[i] = this.jjtGetChild(i).interpret().toString();
		  //symtab.put(scope, this.jjtGetChild(i).interpret().toString(), new VariableValue(null));
		  symtab.put(varNames[i], new VariableValue(null));
	  }
	  
	  return varNames;
  }
  
}
/* JavaCC - OriginalChecksum=9444113d2cb39685ef037ba6203c3984 (do not edit this line) */
