/* Generated By:JJTree: Do not edit this line. ASTcomp_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcomp_op extends SimpleNode {
  public ASTcomp_op(int id) {
    super(id);
  }

  public ASTcomp_op(Minimp p, int id) {
    super(p, id);
  }

  public int interpret ()
  {
	  
  }
  
}
/* JavaCC - OriginalChecksum=876b21a8adc2c66e2a673e5f2542546b (do not edit this line) */
