/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

/*
 * Minimp -- An implementation of an imperative subset of Python
 *
 *
 * Copyright (C) 2013, Joseph Heron, Jonathan Gillett, and Daniel Smullen
 * All rights reserved.
 *
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
public
class ASTDeclaration extends SimpleNode {
  public ASTDeclaration(int id) {
    super(id);
  }

  public ASTDeclaration(Minimp p, int id) {
    super(p, id);
  }

  public Object interpret()
  {
	  /* 
	   * This method will identify whether the variable exists or not and will
	   * call add to look it up in the syntax table.
	   */
	  if(this.jjtGetNumChildren() == 0)
	  {
		  for (int i = scope; i >= 0; i--)
		  {
			  if(symtab.get(this.jjtGetValue().toString(), i) != null)
			  {
				  return this.jjtGetValue().toString();
			  }
		  }
		  
		  symtab.put(this.jjtGetValue().toString(), scope, new VariableValue(""));
		  // TODO create a list of variables, to declase in the data section
		  // variable should be called buy <identifier> + "_" + <scope>
		  dataList.add(this.jjtGetValue().toString() + "_" + scope);
		  
		  return this.jjtGetValue().toString();
	  }
	  
	  return null;	
  }
}
/* JavaCC - OriginalChecksum=2cb14ef3df27cd1380ae51fcd2771158 (do not edit this line) */
