/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclaration extends SimpleNode {
  public ASTDeclaration(int id) {
    super(id);
  }

  public ASTDeclaration(Minimp p, int id) {
    super(p, id);
  }

  public Object interpret()
  {
	  /* 
	   * This method will identify whether the variable exists or not and will
	   *  call add look it up in the syntax table.
	   */
	  if(this.jjtGetNumChildren() == 0)
	  {
		  
		  symtab.put(this.jjtGetValue().toString(), new VariableValue(0, SimpleNode.scope));
		  return this.jjtGetValue().toString();
	  }
	  
	  return null;	
  }
}
/* JavaCC - OriginalChecksum=2cb14ef3df27cd1380ae51fcd2771158 (do not edit this line) */
