/* Generated By:JJTree: Do not edit this line. ASTequal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTequal extends SimpleNode {
  public ASTequal(int id) {
    super(id);
  }

  public ASTequal(Minimp p, int id) {
    super(p, id);
  }
  
  public Object interpret()
  {
	  if(this.jjtGetNumChildren() > 0 && this.jjtGetNumChildren() < 3)
	  {
		  // First child is the left side of the equal sign
		  
		  // The second child is the right side of the equal sign  
		  Integer value = Integer.valueOf(this.jjtGetChild(1).interpret().toString());
		  
		  // Validate the variable
		  String variable = this.jjtGetChild(0).interpret().toString();
		  
		  //System.out.println("Variable " + variable + " value " + value);
		  
		  // Find variable in hash and assign value to it.
		  // Adjust to use the defined variable.
		  
		  for (int i = scope; i >= 0; i--)
		  {
			 // System.out.println("HERE");
			  if(symtab.get(variable, i) != null)
			  {
				  //System.out.println(symtab.get(variable, i));
				  symtab.put(variable, i, new VariableValue(value));
			  }	
		  }
		  		  
		  // Valid
		  return null;
	  }
	  
	  // ERROR
	  return null;
  }
}
/* JavaCC - OriginalChecksum=3a39fcc0d48e078fb5f3cb835fd6a00c (do not edit this line) */
