/* Generated By:JJTree: Do not edit this line. ASTelse_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

/*
 * Minimp -- An implementation of an imperative subset of Python
 *
 *
 * Copyright (C) 2013, Joseph Heron, Jonathan Gillett, and Daniel Smullen
 * All rights reserved.
 *
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
public
class ASTelse_statement extends SimpleNode {
  public ASTelse_statement(int id) {
    super(id);
  }

  public ASTelse_statement(Minimp p, int id) {
    super(p, id);
  }
  
  public Object interpret()
  {
	  if(this.jjtGetNumChildren() > 0)
	  {
		  scope++;
		  
		  for(int i = 0; i < this.jjtGetNumChildren(); i++)
		  {
			  Object returnValue = this.jjtGetChild(i).interpret();
			  if(returnValue != null)
			  {
				  scope--;
				  return returnValue;
			  }
		  }
		  
		  scope--;
		  return null;

	  }
	  
	  // Error
	  return null;
  }
  
}
/* JavaCC - OriginalChecksum=215fb746e4811cb9d39d24c4fed2ad32 (do not edit this line) */
