/* Generated By:JJTree: Do not edit this line. ASTFuncVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

/*
 * Minimp -- An implementation of an imperative subset of Python
 *
 *
 * Copyright (C) 2013, Joseph Heron, Jonathan Gillett, and Daniel Smullen
 * All rights reserved.
 *
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
public
class ASTFuncVariable extends SimpleNode {
  public ASTFuncVariable(int id) {
    super(id);
  }

  public ASTFuncVariable(Minimp p, int id) {
    super(p, id);
  }
  
  public Object interpret()
  {
	  /* 
	   * This method will identify whether the variable exists or not and will
	   *  call add look it up in the syntax table.
	   */
	  if(this.jjtGetNumChildren() == 0)
	  {
		  symtab.put(this.jjtGetValue().toString(), scope, new VariableValue(""));
		  return this.jjtGetValue().toString();
	  }
	  
	  return null;
  }

}
/* JavaCC - OriginalChecksum=e3ef54118cfb13d0e71b2e1dc5900e71 (do not edit this line) */
