/* Generated By:JJTree: Do not edit this line. ASTFuncVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFuncVariable extends SimpleNode {
  public ASTFuncVariable(int id) {
    super(id);
  }

  public ASTFuncVariable(Minimp p, int id) {
    super(p, id);
  }
  
  public Object interpret()
  {
	  /* 
	   * This method will identify whether the variable exists or not and will
	   *  call add look it up in the syntax table.
	   */
	  if(this.jjtGetNumChildren() == 0)
	  {
		  symtab.put(this.jjtGetValue().toString(), scope, new VariableValue(0));
		  //symtab.put(scope, this.jjtGetValue().toString(), new VariableValue(0));
		  return this.jjtGetValue().toString();
	  }
	  
	  return null;	
  }

}
/* JavaCC - OriginalChecksum=e3ef54118cfb13d0e71b2e1dc5900e71 (do not edit this line) */
