import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. ASTlist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTlist extends SimpleNode {
  public ASTlist(int id) {
    super(id);
  }

  public ASTlist(Minimp p, int id) {
    super(p, id);
  }
  
  public Object interpret()
  {
	  if(this.jjtGetNumChildren() > 0)
	  {
		  //String elements = "[";
		  
		  //String regValue = regValues.pop();
		  //System.out.println("la " + regValue + ", " + SLEFTB);
		  
		  ArrayList<String> regValue = new ArrayList<String>();
		  for(int i = 0; i < this.jjtGetNumChildren(); i++)
		  {
			  regValue.add(regValues.pop());
			  
			  System.out.println("li " + regValue.get(i) + ", " + this.jjtGetChild(i).interpret());
			  //elements+= this.jjtGetChild(i).interpret();
			  
			  /*if(i < this.jjtGetNumChildren()-1)
			  {
				  elements += " ";
			  }*/
		  }
		  
		  return regValue;
		  
		  //return elements + "]";
	  }
	  return null;
  }

}
/* JavaCC - OriginalChecksum=2c1d63c466854a92911ac9ccd8cd36f9 (do not edit this line) */
