import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. ASTlist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTlist extends SimpleNode {
  public ASTlist(int id) {
    super(id);
  }

  public ASTlist(Minimp p, int id) {
    super(p, id);
  }
  
  public Object interpret()
  {
	  if(this.jjtGetNumChildren() > 0)
	  {		  
		  ArrayList<TypeValue> regValue = new ArrayList<TypeValue>();
		  for(int i = 0; i < this.jjtGetNumChildren(); i++)
		  {
			  //regValue.add(regValues.pop());
			  Object returnValue = this.jjtGetChild(i).interpret();
			  
			  //if(returnValue.getClass())
			  if(returnValue.getClass().isAssignableFrom(VariableValue.class))
			  {
				  regValue.add((VariableValue)returnValue);
			  }
			  else if(returnValue.getClass().isAssignableFrom(CompareValue.class))
			  {
				  regValue.add((CompareValue)returnValue);
			  }
			  else
			  {
				  String tempValue = regValues.pop();
				  asmBuffer.add("li " + tempValue + ", " + returnValue.toString());
				  regValue.add(new VariableValue(tempValue));
			  }
		  }
		  
		  return regValue;
	  }
	  return null;
  }

}
/* JavaCC - OriginalChecksum=2c1d63c466854a92911ac9ccd8cd36f9 (do not edit this line) */
