/* Generated By:JJTree: Do not edit this line. ASTmul_div_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

/*
 * Minimp -- An implementation of an imperative subset of Python
 *
 *
 * Copyright (C) 2013, Joseph Heron, Jonathan Gillett, and Daniel Smullen
 * All rights reserved.
 *
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
public
class ASTmul_div_op extends SimpleNode {
  public ASTmul_div_op(int id) {
    super(id);
  }

  public ASTmul_div_op(Minimp p, int id) {
    super(p, id);
  }

  public Object interpret()
  {
	  if(this.jjtGetNumChildren() == 2)
	  {
		  String regTemp = regValues.pop();
		  if(this.jjtGetValue().toString().equalsIgnoreCase("*"))
		  {
			  Object returnValue = this.jjtGetChild(0).interpret();
			  String regValue;
			 
			  try
			  {
				  Integer.valueOf(returnValue.toString());
				  regValue = regValues.pop();
				  asmBuffer.add("li " + regValue + ", " + returnValue);
			  }
			  catch (Exception e)
			  {
				  regValue = returnValue.toString();
			  }
			  
			  asmBuffer.add("mul " + regTemp + ", " + regValue + ", " +
					  this.jjtGetChild(1).interpret().toString());
			  
			  regValues.push(regValue);
			  
			  return new VariableValue(regTemp);
			  //return Integer.valueOf(this.jjtGetChild(0).interpret().toString()) *
				//	  Integer.valueOf(this.jjtGetChild(1).interpret().toString()); 
		  }
		  else if(this.jjtGetValue().toString().equalsIgnoreCase("/"))
		  {
			  Object returnValue = this.jjtGetChild(0).interpret();
			  String regValue;
			 
			  try
			  {
				  Integer.valueOf(returnValue.toString());
				  regValue = regValues.pop();
				  asmBuffer.add("li " + regValue + ", " + returnValue);
			  }
			  catch (Exception e)
			  {
				  regValue = returnValue.toString();
			  }
			  
			  asmBuffer.add("div " + regTemp + ", " + regValue + ", " +
					  this.jjtGetChild(1).interpret().toString());
			  
			  regValues.push(regValue);
			  
			  return new VariableValue(regTemp);
			  //return Integer.valueOf(this.jjtGetChild(0).interpret().toString()) /
				//	  Integer.valueOf(this.jjtGetChild(1).interpret().toString());
		  }
		  else
		  {
			  // ERROR
			  return null;
		  }
	  }
	  
	  // ERROR	  
	  return null;
  }

}
/* JavaCC - OriginalChecksum=2aa6de102b86dff7b73bc34103216fd3 (do not edit this line) */
