/* Generated By:JJTree: Do not edit this line. ASTNewVar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNewVar extends SimpleNode {
  public ASTNewVar(int id) {
    super(id);
  }

  public ASTNewVar(Minimp p, int id) {
    super(p, id);
  }
  
  public Object interpret()
  {
	  /* 
	   * This method will identify whether the variable exists or not and will
	   *  call add look it up in the syntax table.
	   */ 
	  if(this.jjtGetNumChildren() == 0)
	  {
		  // Look up variable in table
		  
		  // Variable not found
		  if(false)
		  {
			  // Add the value to the syntax table
		  }
		  
		  //return the value the variable.
	  }
	  
	  return null;	
  }

}
/* JavaCC - OriginalChecksum=761ccd3d14cc1f56144ddfe327e73f34 (do not edit this line) */
