/* Generated By:JJTree: Do not edit this line. ASTNumber.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNumber extends SimpleNode {
  public ASTNumber(int id) {
    super(id);
  }

  public ASTNumber(Minimp p, int id) {
    super(p, id);
  }
  
  @Override
  public Object interpret()
  {
	  return this.jjtGetValue();
  }

}
/* JavaCC - OriginalChecksum=d085c22fe10bcd1e4e13af4bd912a50e (do not edit this line) */
