/* Generated By:JJTree: Do not edit this line. ASTreturn_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

/*
 * Minimp -- An implementation of an imperative subset of Python
 *
 *
 * Copyright (C) 2013, Joseph Heron, Jonathan Gillett, and Daniel Smullen
 * All rights reserved.
 *
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
public
class ASTreturn_op extends SimpleNode {
  public ASTreturn_op(int id) {
    super(id);
  }

  public ASTreturn_op(Minimp p, int id) {
    super(p, id);
  }
  
  public Object interpret()
  {
	  Node parent= this.jjtGetParent();
	  
	  while(parent != null && !ASTdef_statement.class.isAssignableFrom(parent.getClass()))
	  {
		  parent = parent.jjtGetParent();
	  }
	  
	  // return is not defined within a a function's scope
	  if(parent == null)
	  {
		  // ERROR 
		  return null;
	  }
	  
	  Object returnValue = this.jjtGetChild(0).interpret();
	  return returnValue;
  }

}
/* JavaCC - OriginalChecksum=8cad1ee2a8ff9251b3319df33ebbd2fc (do not edit this line) */
