/* Generated By:JJTree: Do not edit this line. ASTreturn_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTreturn_op extends SimpleNode {
  public ASTreturn_op(int id) {
    super(id);
  }

  public ASTreturn_op(Minimp p, int id) {
    super(p, id);
  }
  
  public Object interpret()
  {
	  Node parent= this.jjtGetParent();
	  
	  while(!ASTdef_statement.class.isAssignableFrom(parent.getClass()) && parent != null)
	  {
		  parent = parent.jjtGetParent();
	  }
	  
	  // return is not defined within a a function's scope
	  if(parent == null)
	  {
		  // TODO throw an ERROR 
		  return null;
	  }
	  return this.jjtGetChild(0).interpret();
  }

}
/* JavaCC - OriginalChecksum=8cad1ee2a8ff9251b3319df33ebbd2fc (do not edit this line) */
