/* Generated By:JJTree: Do not edit this line. ASTseq_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTseq_list extends SimpleNode {
  public ASTseq_list(int id) {
    super(id);
  }

  public ASTseq_list(Minimp p, int id) {
    super(p, id);
  }

  public Object interpret()
  {
	  // Add function node to hash table so it can be called later 
	  return null;
  }
  
}
/* JavaCC - OriginalChecksum=f5606e6fd292952468dc335486a10f52 (do not edit this line) */
