/* Generated By:JJTree: Do not edit this line. ASTvar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvar extends SimpleNode {
  public ASTvar(int id) {
    super(id);
  }
  
  public ASTvar(Minimp p, int id) {
    super(p, id);
  }

  public Object interpret()
  {
	  // No idea what dfdsfs do
	  
	  return null;
  }
}
/* JavaCC - OriginalChecksum=db34d54a30b154981e1cf184a01acd73 (do not edit this line) */
